#!/usr/bin/env python3
import rospy
from flask import Flask, request
from db_helper.schema import schema

from flask_graphql import GraphQLView

app = Flask(__name__)

app.add_url_rule(
        "/graphql", view_func=GraphQLView.as_view("graphql", schema=schema, graphiql=True)
        )


if __name__ == '__main__':
    port = rospy.get_param("/liability_cacher/web_server/server_port")
    app.run(port=int(port))

