#!/usr/bin/env python3
import rospy
from flask import Flask, request
from flask_cors import CORS
from helpers.schema import schema

from flask_graphql import GraphQLView

app = Flask(__name__)
CORS(app)

app.add_url_rule(
        "/graphql", view_func=GraphQLView.as_view("graphql", schema=schema, graphiql=True)
        )


if __name__ == '__main__':
    rospy.init_node("web_server")
    host = rospy.get_param("/liability_cacher/web_server/host")
    port = rospy.get_param("/liability_cacher/web_server/server_port")

    app.run(host=host, port=int(port))

